{% set name = "tile_mate" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95d2f74138ea49164f2a5f70f37fd89ac0a6b3560b8bdb88645b19891edfd643

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - python-build
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - rasterio
    - tqdm
    - geopandas
    - importlib-metadata
    - matplotlib-base
    - numpy
    - pandas
    - pandera
    - shapely
    - dem_stitcher >=2.5.4

test:
  imports:
    - tile_mate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OPERA-Cal-Val/tile-mate
  summary: Create rasters from global tiles
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - taliboliver
    - richw7185
    - cmarshak
    - jhkennedy
